# Generated by Django 5.2.14 on 2026-05-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnaeMccMapping',
            fields=[
                ('cod_cnae', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc_cnae', models.TextField()),
                ('cod_mcc', models.IntegerField()),
            ],
            options={
                'db_table': 'cnae_mcc_mapping',
            },
        ),
    ]
