# Generated by Django 5.2.14 on 2026-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnaemccmapping',
            name='id',
            field=models.BigIntegerField(default=0),
        ),
    ]
