# Generated by Django 5.2.14 on 2026-05-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0002_add_id_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnaemccmapping',
            name='cod_cnae',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cnaemccmapping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
