# Generated by Django 5.2.1 on 2026-06-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0005_acquirer_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CPF', 'Cpf'), ('CNPJ', 'Cnpj')], max_length=4)),
                ('document', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('own_status', models.CharField(choices=[('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='quickportal.cnaemccmapping')),
            ],
            options={
                'db_table': 'business',
            },
        ),
    ]
