# Generated by Django 5.2.1 on 2026-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0006_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.CharField(max_length=200)),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'pix'), (2, 'debit'), (3, 'credit'), (4, 'installmentsA'), (5, 'installmentsB'), (6, 'installmentsC'), (7, 'installmentsD')])),
                ('network', models.PositiveSmallIntegerField(choices=[(1, 'mastercard'), (2, 'visa'), (3, 'elo'), (4, 'N/A'), (5, 'pix')])),
                ('value', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
            options={
                'db_table': 'load_fee',
                'unique_together': {('mcc', 'method', 'network')},
            },
        ),
    ]
