# Generated by Django 5.2.1 on 2026-06-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0007_loadfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixPix', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('mastercardDebit', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('visaDebit', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('eloDebit', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('mastercardCredit', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('visaCredit', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('eloCredit', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('mastercardInstallmentsA', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('visaInstallmentsA', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('eloInstallmentsA', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('mastercardInstallmentsB', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('visaInstallmentsB', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('eloInstallmentsB', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('mastercardInstallmentsC', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('visaInstallmentsC', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('eloInstallmentsC', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('mastercardInstallmentsD', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('visaInstallmentsD', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('eloInstallmentsD', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'fee',
            },
        ),
        migrations.CreateModel(
            name='MccFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.CharField(max_length=200, unique=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mccs', to='quickportal.fee')),
            ],
            options={
                'db_table': 'mcc_fee',
            },
        ),
        migrations.DeleteModel(
            name='LoadFee',
        ),
    ]
