# Generated by Django 5.2.1 on 2026-06-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0008_fee_mccfee_delete_loadfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('split', models.BooleanField(default=False)),
                ('anticipation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='quickportal.mccfee')),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('mastercard', 'Mastercard'), ('visa', 'Visa'), ('elo', 'Elo'), ('pix', 'Pix')], max_length=20)),
                ('payment_type', models.CharField(max_length=10)),
                ('commission', models.DecimalField(decimal_places=6, max_digits=10)),
                ('anticipation_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='quickportal.plan')),
            ],
            options={
                'db_table': 'plan_fee',
                'unique_together': {('plan', 'network', 'payment_type')},
            },
        ),
    ]
