# Generated by Django 5.2.1 on 2026-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0009_plan_planfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfee',
            name='anticipation_fee',
        ),
        migrations.AddField(
            model_name='plan',
            name='anticipation_fee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
