# Generated by Django 5.2.1 on 2026-07-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0010_remove_planfee_anticipation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='mcc',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='business',
            name='cod_cnae',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='landline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
