# Generated by Django 5.2.1 on 2026-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0011_remove_business_legal_name_remove_business_mcc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
