# Generated by Django 5.2.1 on 2026-07-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0012_business_trade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
