# Generated by Django 5.2.1 on 2026-07-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0013_alter_business_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='own_status',
            new_name='status',
        ),
    ]
