# Generated by Django 5.2.1 on 2026-07-22 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0014_rename_own_status_business_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispb', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('branch', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('branch_digit', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('account_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('account_digit', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('address_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('projected_revenue', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('commited_revenue', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_of_terminals', models.PositiveIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quickportal.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_details', to='quickportal.plan')),
            ],
            options={
                'db_table': 'business_details',
            },
        ),
        migrations.CreateModel(
            name='PosDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='quickportal.business')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='quickportal.posmodel')),
            ],
            options={
                'db_table': 'pos_device',
                'constraints': [models.UniqueConstraint(fields=('model', 'serial'), name='unique_pos_device_serial')],
            },
        ),
    ]
