# Generated by Django 5.2.1 on 2026-07-22 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0015_businessdetails_posdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quickportal.business'),
        ),
    ]
