# Generated by Django 5.2.1 on 2026-07-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickportal", "0016_alter_businessdetails_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessdetails",
            old_name="ispb",
            new_name="bank_code",
        ),
    ]
