# Generated by Django 5.2.1 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickportal", "0017_rename_businessdetails_ispb_bank_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PENDING", "Pending"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
