# Generated by Django 5.2.1 on 2026-08-03 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def drop_old_fee_data(apps, schema_editor):
    # The old wide fee schema cannot be mapped reliably to the new dimensions.
    # These tables only contain test data, so clear the dependent rows explicitly.
    apps.get_model("quickportal", "BusinessDetails").objects.all().delete()
    apps.get_model("quickportal", "Plan").objects.all().delete()
    apps.get_model("quickportal", "MccFee").objects.all().delete()
    apps.get_model("quickportal", "Fee").objects.all().delete()


class Migration(migrations.Migration):

    # PostgreSQL queues FK trigger events for the cleanup deletes. Committing the
    # cleanup before altering the affected tables avoids pending-trigger errors.
    atomic = False

    dependencies = [
        ('quickportal', '0018_alter_business_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'network',
            },
        ),
        migrations.RunPython(drop_old_fee_data, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='planfee',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fee',
            name='eloCredit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='eloDebit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='eloInstallmentsA',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='eloInstallmentsB',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='eloInstallmentsC',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='eloInstallmentsD',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mastercardCredit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mastercardDebit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mastercardInstallmentsA',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mastercardInstallmentsB',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mastercardInstallmentsC',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mastercardInstallmentsD',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='pixPix',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='visaCredit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='visaDebit',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='visaInstallmentsA',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='visaInstallmentsB',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='visaInstallmentsC',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='visaInstallmentsD',
        ),
        migrations.AddField(
            model_name='fee',
            name='acquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='quickportal.acquirer'),
        ),
        migrations.AddField(
            model_name='fee',
            name='cnae',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')]),
        ),
        migrations.AddField(
            model_name='fee',
            name='installments',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='fee',
            name='value',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AddField(
            model_name='planfee',
            name='fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_fee', to='quickportal.fee'),
        ),
        migrations.AddField(
            model_name='planfee',
            name='value',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AddField(
            model_name='fee',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='quickportal.network'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(fields=('acquirer', 'cnae', 'network', 'installments'), name='unique_fee_dimensions'),
        ),
        migrations.RemoveField(
            model_name='planfee',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='planfee',
            name='network',
        ),
        migrations.RemoveField(
            model_name='planfee',
            name='payment_type',
        ),
    ]
