# Generated by Django 5.2.1 on 2026-08-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0020_client_plan_client_remove_plan_mcc_plan_cnae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfee',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_fees', to='quickportal.fee'),
        ),
        migrations.AddConstraint(
            model_name='planfee',
            constraint=models.UniqueConstraint(fields=('plan', 'fee'), name='unique_plan_fee'),
        ),
    ]
