# Generated by Django 5.2.1 on 2026-08-03 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0021_alter_planfee_fee_planfee_unique_plan_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'This field must contain only digits.')])),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'cnaes',
            },
        ),
    ]
