# Generated by Django 5.2.1 on 2026-08-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickportal', '0022_cnae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
