from django.urls import path

from quickportal.views import (
    AcquirerListView,
    BusinessDetailView,
    BusinessDetailsDetailView,
    BusinessDetailsListCreateView,
    BusinessListCreateView,
    CnaeListView,
    CnaesWithFeesListView,
    EmailTokenObtainPairView,
    FeeListView,
    MerchantRegistrationView,
    NetworkListView,
    OwnAuthTokenView,
    PlanDetailView,
    PlanListCreateView,
    PosModelListView,
    PosDeviceDetailView,
    PosDeviceListCreateView,
    UserRegistrationView,
)

urlpatterns = [
    path("users/register/", UserRegistrationView.as_view()),
    path("api/token/", EmailTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("own/auth/", OwnAuthTokenView.as_view(), name="own_auth"),
    path(
        "own/merchants/register/",
        MerchantRegistrationView.as_view(),
        name="own_merchant_register",
    ),
    path("api/cnaes/", CnaeListView.as_view(), name="cnae_list"),
    path(
        "api/cnaes-with-fees/",
        CnaesWithFeesListView.as_view(),
        name="cnaes_with_fees_list",
    ),
    path("api/fees/", FeeListView.as_view(), name="fee_list"),
    path("api/acquirers/", AcquirerListView.as_view(), name="acquirer_list"),
    path("api/networks/", NetworkListView.as_view(), name="network_list"),
    path("api/pos-models/", PosModelListView.as_view(), name="pos_model_list"),
    path("api/plans/", PlanListCreateView.as_view(), name="plan_list_create"),
    path("api/plans/<int:pk>/", PlanDetailView.as_view(), name="plan_detail"),
    path("api/businesses/", BusinessListCreateView.as_view(), name="business_list_create"),
    path("api/businesses/<int:pk>/", BusinessDetailView.as_view(), name="business_detail"),
    path("api/business-details/", BusinessDetailsListCreateView.as_view(), name="business_details_list_create"),
    path("api/business-details/<int:pk>/", BusinessDetailsDetailView.as_view(), name="business_details_detail"),
    path("api/pos-devices/", PosDeviceListCreateView.as_view(), name="pos_device_list_create"),
    path("api/pos-devices/<int:pk>/", PosDeviceDetailView.as_view(), name="pos_device_detail"),
]
